# https://circleci.com/docs/2.0/configuration-reference/#storetestresults
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      # A special step used to check out source code to the configured path (defaults to the working_directory). The reason this is a special step is because it is more of a helper function designed to make checking out code easy for you. If you require doing git over HTTPS you should not use this step as it configures git to checkout over ssh.
      - run:
          name: Install Dependencies
          command: . build/install.sh
      - run:
          name: Create Scratch Org
          command: . build/create-scratch-org.sh
      - run:
          name: Validate Components & Run Tests
          command: . build/test.sh
      - run: 
          name: Push to Codecov.io (Optional Step)
          command: |
              cp test-results/test-result-codecoverage.json .
              bash <(curl -s https://codecov.io/bash)
      - store_test_results:
      # Special step used to upload and store test results for a build. Test results are visible on the CircleCI web application, under each build’s “Test Summary” section.
          path: test-results
  deploy-prod:
    docker:
    - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: . build/install.sh
      - run:
          name: Login to Production
          command: . build/setup-prod.sh
      - run:
          name: Deploy to Production
          command: . build/deploy-prod.sh
workflows:
  version: 2
  validate:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
      - deploy-prod:
          filters:
            branches:
              only:
                - master